import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ExportColumn<T> = {
  key: keyof T;
  label: string;
};

type ExportPdfParams<T extends Record<string, string | number>> = {
  fileName?: string;
  filename?: string;
  title: string;
  columns: ExportColumn<T>[];
  rows: T[];
  openInNewTab?: boolean;
};

export function exportToPdf<T extends Record<string, string | number>>({
  fileName,
  filename,
  title,
  columns,
  rows,
  openInNewTab = false,
}: ExportPdfParams<T>) {
  const resolvedFileName = fileName ?? filename ?? "novaops-export";

  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const generatedAt = new Date().toLocaleString();

  doc.setFontSize(18);
  doc.text("NovaOPS Enterprise", 14, 16);

  doc.setFontSize(12);
  doc.text(title, 14, 25);

  doc.setFontSize(9);
  doc.text(`Generated: ${generatedAt}`, 14, 32);
  doc.text("Confidential Operations Report", 14, 38);

  autoTable(doc, {
    startY: 48,
    head: [columns.map((column) => column.label)],
    body: rows.map((row) => columns.map((column) => String(row[column.key] ?? ""))),
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [61, 107, 73],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    didDrawPage: () => {
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      doc.setFontSize(8);
      doc.text("Generated by NovaOPS Enterprise", 14, pageHeight - 10);
      doc.text(`Page ${doc.getNumberOfPages()}`, pageWidth - 30, pageHeight - 10);
    },
  });

  if (openInNewTab) {
    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank");
    return;
  }

  doc.save(`${resolvedFileName}.pdf`);
}
