import { OutletTaskStoreItem } from "./types";

export const initialOutletTaskStoreItems: OutletTaskStoreItem[] = [
  {
    id: "OTF-001",
    outlet: "KOV Montre",
    task: "Opening Readiness",
    form: "Daily Opening Checklist",
    status: "completed",
    progress: 100,
    score: 98,
    operator: "Outlet Operator",
    due: "Today 07:00",
    submittedAt: "Today 06:58",
    updatedAt: "Realtime",
  },
  {
    id: "OTF-002",
    outlet: "KOV Heritage",
    task: "Service Quality Check",
    form: "Service Audit Form",
    status: "submitted",
    progress: 100,
    score: 92,
    operator: "Outlet Operator",
    due: "Today 12:00",
    submittedAt: "Today 11:42",
    updatedAt: "Realtime",
  },
  {
    id: "OTF-003",
    outlet: "KOV Sultan Agung",
    task: "Cleanliness Standard",
    form: "Cleanliness Checklist",
    status: "draft",
    progress: 62,
    score: 62,
    operator: "Outlet Operator",
    due: "Today 16:00",
    submittedAt: "Saved Draft",
    updatedAt: "Realtime",
  },
  {
    id: "OTF-004",
    outlet: "KOV Sula",
    task: "Product Availability",
    form: "Inventory Check Form",
    status: "pending",
    progress: 0,
    score: 0,
    operator: "-",
    due: "Today 18:00",
    submittedAt: "-",
    updatedAt: "Realtime",
  },
];
