import { OutletTaskStoreItem } from "./types";

export const initialOutletTaskStoreItems: OutletTaskStoreItem[] = [
  {
    id: "SOP-001",
    outlet: "KOV Montre",
    task: "Daily Opening Readiness",
    form: "Daily Opening Checklist",
    status: "completed",
    progress: 100,
    score: 98,
    operator: "Fajar",
    due: "Today 07:00",
    submittedAt: "Today 06:58",
    updatedAt: "Realtime",
    correctiveActionStatus: "none",
  },
  {
    id: "SOP-002",
    outlet: "KOV Heritage",
    task: "Lunch Rush Service Quality",
    form: "Outlet Operational Audit",
    status: "submitted",
    progress: 100,
    score: 92,
    operator: "Maya",
    due: "Today 12:00",
    submittedAt: "Today 11:42",
    updatedAt: "Realtime",
    correctiveActionStatus: "none",
  },
  {
    id: "SOP-003",
    outlet: "KOV Sultan Agung",
    task: "Espresso Machine Cleaning",
    form: "Cleaning Audit",
    status: "draft",
    progress: 62,
    score: 62,
    operator: "Raka",
    due: "Today 16:00",
    submittedAt: "Saved Draft",
    updatedAt: "Realtime",
    correctiveActionStatus: "open",
    correctiveActionOwner: "Store Manager",
    correctiveActionDue: "Today 18:00",
    correctiveActionNote: "Complete machine cleaning evidence and upload after photo.",
  },
  {
    id: "SOP-004",
    outlet: "KOV Sula",
    task: "Milk & Syrup Availability",
    form: "Inventory Variance Check",
    status: "pending",
    progress: 0,
    score: 0,
    operator: "-",
    due: "Today 18:00",
    submittedAt: "-",
    updatedAt: "Realtime",
    correctiveActionStatus: "none",
  },
  {
    id: "SOP-005",
    outlet: "KOV Heritage",
    task: "Restroom Cleanliness Audit",
    form: "Cleaning Audit",
    status: "overdue",
    progress: 35,
    score: 35,
    operator: "Dina",
    due: "Today 10:00",
    submittedAt: "Saved Draft",
    updatedAt: "Realtime",
    correctiveActionStatus: "open",
    correctiveActionOwner: "Area Manager",
    correctiveActionDue: "Today 15:00",
    correctiveActionNote: "Restroom audit overdue. Request immediate completion and photo evidence.",
  },
  {
    id: "SOP-006",
    outlet: "KOV Montre",
    task: "Product Sample Quality Check",
    form: "Outlet Operational Audit",
    status: "submitted",
    progress: 100,
    score: 74,
    operator: "Nadia",
    due: "Today 14:00",
    submittedAt: "Today 13:50",
    updatedAt: "Realtime",
    correctiveActionStatus: "open",
    correctiveActionOwner: "Quality Lead",
    correctiveActionDue: "Tomorrow 10:00",
    correctiveActionNote: "Low product sample score. Re-train recipe standard and submit repeat audit.",
  },
  {
    id: "SOP-007",
    outlet: "KOV Sultan Agung",
    task: "Closing Cashier Checklist",
    form: "Daily Opening Checklist",
    status: "pending",
    progress: 0,
    score: 0,
    operator: "-",
    due: "Today 22:00",
    submittedAt: "-",
    updatedAt: "Realtime",
    correctiveActionStatus: "none",
  },
  {
    id: "SOP-008",
    outlet: "KOV Sula",
    task: "Bar Area Photo Evidence",
    form: "Daily Opening Checklist",
    status: "completed",
    progress: 100,
    score: 96,
    operator: "Adit",
    due: "Today 08:00",
    submittedAt: "Today 07:51",
    updatedAt: "Realtime",
    correctiveActionStatus: "resolved",
    correctiveActionOwner: "Store Manager",
    correctiveActionDue: "Today 09:00",
    correctiveActionNote: "Opening photo evidence reviewed and accepted.",
    correctiveActionResolvedAt: "Today 08:20",
  },
];