import { ProjectTask } from "./types";

export const NOVAOPS_REAL_PROJECT_TASKS: ProjectTask[] = [
  {
    id: "06i5-auto-save-draft",
    title: "Auto Save Draft Engine",
    sprint: "06I.5",
    module: "Task UX",
    status: "completed",
  },
  {
    id: "06i5-save-indicator",
    title: "Save Indicator",
    sprint: "06I.5",
    module: "Task UX",
    status: "completed",
  },
  {
    id: "06i5-dynamic-form-progress",
    title: "Dynamic Form Progress Engine",
    sprint: "06I.5",
    module: "Forms",
    status: "completed",
  },
  {
    id: "06i5-progress-bar-chip",
    title: "Progress Bar + Progress Chip",
    sprint: "06I.5",
    module: "Forms",
    status: "completed",
  },
  {
    id: "06i5-sectioned-form-renderer",
    title: "Sectioned Form Renderer",
    sprint: "06I.5",
    module: "Forms",
    status: "completed",
  },
  {
    id: "06i5-unsaved-guard",
    title: "Unsaved Changes Guard",
    sprint: "06I.5",
    module: "Task UX",
    status: "completed",
  },
  {
    id: "06i5-continue-draft",
    title: "Continue Draft Highlight + Auto Scroll",
    sprint: "06I.5",
    module: "Draft",
    status: "completed",
  },
  {
    id: "06i5-draft-badge",
    title: "Draft Badge Percentage",
    sprint: "06I.5",
    module: "Draft",
    status: "completed",
  },
  {
    id: "06i5-evidence-gallery",
    title: "Evidence Gallery Component",
    sprint: "06I.5",
    module: "Evidence",
    status: "completed",
  },
  {
    id: "06i5-skeleton-loading",
    title: "Skeleton Loading",
    sprint: "06I.5",
    module: "UX",
    status: "completed",
  },
  {
    id: "06i5-premium-drawer",
    title: "Premium Drawer Animation + Sticky Header/Footer",
    sprint: "06I.5",
    module: "UX",
    status: "completed",
  },
  {
    id: "06i5-error-scroll",
    title: "Submit Error Auto Scroll + Field Highlight",
    sprint: "06I.5",
    module: "Validation",
    status: "completed",
  },
  {
    id: "06j-shared-workflow",
    title: "Shared Workflow Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-status-types",
    title: "Workflow Status Types",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-transition-engine",
    title: "Status Transition Engine",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-assignment-engine",
    title: "Assignment Engine Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-sla-foundation",
    title: "SLA Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-timeline-foundation",
    title: "Timeline Event Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-notification-foundation",
    title: "Notification Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "06j-task-inbox-foundation",
    title: "Task Inbox Foundation",
    sprint: "06J",
    module: "Workflow",
    status: "completed",
  },
  {
    id: "07-backend-integration",
    title: "Enterprise Backend Integration",
    sprint: "07",
    module: "Backend",
    status: "planned",
  },
];
