import {
  BarChart3,
  Banknote,
  Bell,
  Building2,
  ClipboardCheck,
  ClipboardList,
  CalendarClock,
  Camera,
  FileText,
  Gauge,
  GitBranch,
  Grid2X2,
  History,
  Siren,
  LayoutDashboard,
  MailCheck,
  Megaphone,
  PackageCheck,
  Radio,
  Server,
  Settings,
  ShoppingCart,
  Smartphone,
  Store,
  ShieldAlert,
  Thermometer,
  GraduationCap,
  MoreHorizontal,
  Users,
  Wrench,
} from "lucide-react";

export type NavigationItem = {
  id: string;
  label: string;
  href: string;
  icon: typeof LayoutDashboard;
  requiredPermissions: string[];
  section: "sop" | "analytics" | "administration" | "configuration";
  sidebar?: boolean;
};

export const navigationItems: NavigationItem[] = [
  {
    id: "operator",
    label: "Beranda Outlet",
    href: "/dashboard/operator",
    icon: Store,
    requiredPermissions: ["task.read"],
    section: "sop",
  },
  {
    id: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    requiredPermissions: ["report.read"],
    section: "sop",
  },
  {
    id: "compliance",
    label: "Compliance",
    href: "/dashboard/compliance",
    icon: Gauge,
    requiredPermissions: ["report.read"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "exceptions",
    label: "Review Queue",
    href: "/dashboard/exceptions",
    icon: ShieldAlert,
    requiredPermissions: ["report.read"],
    section: "analytics",
  },
  {
    id: "tasks",
    label: "Task",
    href: "/dashboard/tasks",
    icon: ClipboardCheck,
    requiredPermissions: ["task.read"],
    section: "sop",
    sidebar: true,
  },
  {
    id: "schedules",
    label: "Schedules",
    href: "/dashboard/schedules",
    icon: CalendarClock,
    requiredPermissions: ["task.read"],
    section: "sop",
  },
  {
    id: "forms",
    label: "My Form",
    href: "/dashboard/forms",
    icon: FileText,
    requiredPermissions: ["form.read"],
    section: "sop",
  },
  {
    id: "field-audits",
    label: "Field Audits",
    href: "/dashboard/field-audits",
    icon: ClipboardList,
    requiredPermissions: ["task.read"],
    section: "sop",
  },
  {
    id: "corrective-actions",
    label: "Corrective Actions",
    href: "/dashboard/corrective-actions",
    icon: Wrench,
    requiredPermissions: ["task.read"],
    section: "sop",
  },
  {
    id: "incidents",
    label: "Incidents",
    href: "/dashboard/incidents",
    icon: Siren,
    requiredPermissions: ["incident.read"],
    section: "sop",
    // Keep for outlet More + manager Modules; hide from primary sidebar.
    sidebar: false,
  },
  {
    id: "evidence",
    label: "Evidence",
    href: "/dashboard/reports?tab=bukti",
    icon: Camera,
    requiredPermissions: ["report.read"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "drafts",
    label: "Draft",
    href: "/dashboard/drafts",
    icon: FileText,
    requiredPermissions: ["task.execute"],
    section: "sop",
    sidebar: false,
  },
  {
    id: "outlets",
    label: "Outlets",
    href: "/dashboard/outlets",
    icon: Building2,
    requiredPermissions: ["outlet.read"],
    section: "administration",
  },
  {
    id: "outlet-profile",
    label: "Outlet Profile",
    href: "/dashboard/outlet-profile",
    icon: Store,
    requiredPermissions: ["outlet.read"],
    section: "administration",
    sidebar: false,
  },
  {
    id: "ops-suite",
    label: "Ops Suite",
    href: "/dashboard/ops-suite",
    icon: PackageCheck,
    requiredPermissions: ["report.read"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "enterprise-suite",
    label: "Enterprise Suite",
    href: "/dashboard/enterprise-suite",
    icon: ShoppingCart,
    requiredPermissions: ["report.read"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "finance",
    label: "Finance Dashboard",
    href: "/dashboard/finance",
    icon: LayoutDashboard,
    requiredPermissions: ["finance.read"],
    section: "analytics",
  },
  {
    id: "finance-handoff",
    label: "Finance Reports",
    href: "/dashboard/finance-handoff",
    icon: Banknote,
    requiredPermissions: ["finance.read"],
    section: "analytics",
  },
  {
    id: "activity",
    label: "Activity Feed",
    href: "/dashboard/activity",
    icon: Radio,
    requiredPermissions: ["task.read"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "announcements",
    label: "Announcements",
    href: "/dashboard/announcements",
    icon: Megaphone,
    requiredPermissions: ["notification.read"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/dashboard/notifications",
    icon: Bell,
    requiredPermissions: ["notification.read"],
    section: "analytics",
  },
  {
    id: "reports",
    label: "Reports",
    href: "/dashboard/reports",
    icon: BarChart3,
    requiredPermissions: ["report.read"],
    section: "analytics",
  },
  {
    id: "benchmarks",
    label: "Benchmarks",
    href: "/dashboard/benchmarks",
    icon: BarChart3,
    requiredPermissions: ["report.read"],
    section: "analytics",
  },
  {
    id: "report-automation",
    label: "Report Automation",
    href: "/dashboard/report-automation",
    icon: MailCheck,
    requiredPermissions: ["report.read"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "audit",
    label: "Audit Trail",
    href: "/dashboard/audit",
    icon: History,
    requiredPermissions: ["user.edit"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "history",
    label: "History",
    href: "/dashboard/reports?tab=riwayat",
    icon: History,
    requiredPermissions: ["task.execute"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "accounts",
    label: "Accounts",
    href: "/dashboard/users",
    icon: Users,
    requiredPermissions: ["user.read"],
    section: "administration",
  },
  {
    id: "workflows",
    label: "Workflows",
    href: "/dashboard/workflows",
    icon: GitBranch,
    requiredPermissions: ["user.edit"],
    section: "administration",
    sidebar: false,
  },
  {
    id: "webhooks",
    label: "Webhooks",
    href: "/dashboard/webhooks",
    icon: Bell,
    requiredPermissions: ["user.edit"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "ops-health",
    label: "Ops Health",
    href: "/dashboard/ops-health",
    icon: Server,
    requiredPermissions: ["user.edit"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "iot",
    label: "IoT Sensors",
    href: "/dashboard/iot",
    icon: Thermometer,
    requiredPermissions: ["report.read"],
    section: "analytics",
    sidebar: false,
  },
  {
    id: "training",
    label: "Training",
    href: "/dashboard/training",
    icon: GraduationCap,
    requiredPermissions: ["task.read"],
    section: "sop",
    sidebar: false,
  },
  {
    id: "mobile-app",
    label: "Mobile App",
    href: "/dashboard/mobile-app",
    icon: Smartphone,
    requiredPermissions: ["user.edit"],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "settings",
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    requiredPermissions: [],
    section: "configuration",
  },
  {
    id: "more",
    label: "More",
    href: "/dashboard/more",
    icon: MoreHorizontal,
    requiredPermissions: [],
    section: "configuration",
    sidebar: false,
  },
  {
    id: "modules",
    label: "More",
    href: "/dashboard/modules",
    icon: Grid2X2,
    requiredPermissions: [],
    section: "configuration",
  },
];

export const navigationSectionLabels: Record<NavigationItem["section"], string> = {
  sop: "Execution",
  analytics: "Review",
  administration: "Administration",
  configuration: "Configuration",
};
