import {
  BarChart3,
  Building2,
  ClipboardCheck,
  FileText,
  Home,
  Plus,
  Search,
  Settings,
  Users,
} from "lucide-react";
import { CommandItem } from "./types";

export const commandItems: CommandItem[] = [
  {
    id: "go-dashboard",
    title: "Go to Dashboard",
    description: "Open enterprise dashboard",
    href: "/dashboard",
    group: "Navigation",
    type: "navigation",
    icon: Home,
  },
  {
    id: "go-tasks",
    title: "Go to SOP Tasks",
    description: "Open SOP execution workspace",
    href: "/dashboard/tasks",
    group: "Navigation",
    type: "navigation",
    icon: ClipboardCheck,
  },
  {
    id: "go-forms",
    title: "Go to SOP Forms",
    description: "Open checklist and audit template builder",
    href: "/dashboard/forms",
    group: "Navigation",
    type: "navigation",
    icon: FileText,
  },
  {
    id: "go-reports",
    title: "Go to Reports",
    description: "Open reporting and analytics",
    href: "/dashboard/reports",
    group: "Navigation",
    type: "navigation",
    icon: BarChart3,
  },
  {
    id: "go-outlets",
    title: "Go to Outlets",
    description: "Open multi-outlet management",
    href: "/dashboard/outlets",
    group: "Navigation",
    type: "navigation",
    icon: Building2,
  },
  {
    id: "go-users",
    title: "Go to Users",
    description: "Open user administration",
    href: "/dashboard/users",
    group: "Navigation",
    type: "navigation",
    icon: Users,
  },
  {
    id: "go-settings",
    title: "Go to Settings",
    description: "Open organization settings",
    href: "/dashboard/settings",
    group: "Navigation",
    type: "navigation",
    icon: Settings,
  },
  {
    id: "create-task",
    title: "Create SOP Task",
    description: "Assign a checklist or audit to an outlet",
    href: "/dashboard/tasks",
    group: "Quick Actions",
    type: "action",
    icon: Plus,
  },
  {
    id: "create-draft",
    title: "Create Draft",
    description: "Open draft center",
    href: "/dashboard/drafts",
    group: "Quick Actions",
    type: "action",
    icon: FileText,
  },
  {
    id: "search-reports",
    title: "Search Reports",
    description: "Find submitted reports and analytics",
    href: "/dashboard/reports",
    group: "Search",
    type: "report",
    icon: Search,
  },
];


