import {
  BarChart3,
  Banknote,
  Building2,
  ClipboardCheck,
  FileText,
  Home,
  Settings,
  Bell,
  CalendarClock,
  ShieldAlert,
  Wrench,
  Users,
} from "lucide-react";
import { CommandItem } from "./types";

export const commandItems: CommandItem[] = [
  {
    id: "go-dashboard",
    title: "Go to Dashboard",
    description: "Open executive operations snapshot",
    href: "/dashboard",
    group: "Navigation",
    type: "navigation",
    icon: Home,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-tasks",
    title: "Go to Task",
    description: "Open unified task execution workspace",
    href: "/dashboard/tasks",
    group: "Navigation",
    type: "navigation",
    icon: ClipboardCheck,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "OUTLET"],
  },
  {
    id: "go-forms",
    title: "Go to My Form",
    description: "Open reusable form template library",
    href: "/dashboard/forms",
    group: "Navigation",
    type: "navigation",
    icon: FileText,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "OUTLET"],
  },
  {
    id: "go-reports",
    title: "Go to Reports",
    description: "Open submitted work, evidence, and exports",
    href: "/dashboard/reports",
    group: "Navigation",
    type: "navigation",
    icon: BarChart3,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "OUTLET"],
  },
  {
    id: "go-review-queue",
    title: "Go to Review Queue",
    description: "Open exceptions that need action",
    href: "/dashboard/exceptions",
    group: "Navigation",
    type: "navigation",
    icon: ShieldAlert,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-schedules",
    title: "Go to Schedules",
    description: "Open recurring task schedules",
    href: "/dashboard/schedules",
    group: "Navigation",
    type: "navigation",
    icon: CalendarClock,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-corrective-actions",
    title: "Go to Corrective Actions",
    description: "Open corrective action follow-up",
    href: "/dashboard/corrective-actions",
    group: "Navigation",
    type: "navigation",
    icon: Wrench,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-notifications",
    title: "Go to Notifications",
    description: "Open notification inbox",
    href: "/dashboard/notifications",
    group: "Navigation",
    type: "navigation",
    icon: Bell,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "OUTLET", "FINANCE"],
  },
  {
    id: "go-outlets",
    title: "Go to Outlets",
    description: "Open multi-outlet management",
    href: "/dashboard/outlets",
    group: "Navigation",
    type: "navigation",
    icon: Building2,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-finance-handoff",
    title: "Go to Finance Reports",
    description: "Open shift deposit and finance review",
    href: "/dashboard/finance-handoff",
    group: "Navigation",
    type: "navigation",
    icon: Banknote,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "FINANCE"],
  },
  {
    id: "go-users",
    title: "Go to Users",
    description: "Open user administration",
    href: "/dashboard/users",
    group: "Navigation",
    type: "navigation",
    icon: Users,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER"],
  },
  {
    id: "go-settings",
    title: "Go to Settings",
    description: "Open organization settings",
    href: "/dashboard/settings",
    group: "Navigation",
    type: "navigation",
    icon: Settings,
    allowedRoles: ["OWNER_ADMIN", "AREA_MANAGER", "OUTLET"],
  },
];
