import { api } from "@/services/api";
import { cacheTasks, getCachedTasks } from "@/lib/offline/store";
import { taskScheduleService } from "@/services/task-schedule.service";
import type { Task, TaskFormState, TaskPriority, TaskShift, TaskStatus } from "@/features/tasks/types";

export type BackendTaskStatus = "open" | "in_progress" | "blocked" | "completed" | "cancelled";
export type BackendTaskPriority = "low" | "medium" | "high" | "urgent";

export type BackendTask = {
  id: number;
  title: string;
  description: string | null;
  outlet_id: number;
  outlet_name?: string | null;
  assigned_to: number | null;
  created_by: number;
  source_type: string | null;
  source_id: number | null;
  priority: BackendTaskPriority;
  status: BackendTaskStatus;
  due_date: string | null;
  completed_at: string | null;
  approved_by: number | null;
  approved_at: string | null;
  schedule_id: number | null;
  shift: string | null;
  recurrence: "daily" | "weekly" | "once" | null;
  due_time: string | null;
  weekly_publish_day: string | null;
  auto_publish: boolean | null;
  created_at: string;
  updated_at: string;
};

type BackendTaskCreate = {
  title: string;
  description: string | null;
  assigned_to: number | null;
  priority: BackendTaskPriority;
  due_date: string | null;
  source_type: string | null;
  source_id: number | null;
};

type BackendTaskUpdate = Partial<
  Pick<BackendTaskCreate, "title" | "description" | "assigned_to" | "priority" | "due_date">
>;

const LOCAL_FORM_TEMPLATE_PREFIX = "local_form_template:";

function toFrontendStatus(status: BackendTaskStatus): TaskStatus {
  if (status === "completed") return "Completed";
  if (status === "in_progress" || status === "blocked") return "In Progress";
  return "Pending";
}

function toBackendPriority(priority: TaskPriority): BackendTaskPriority {
  if (priority === "Critical") return "urgent";
  if (priority === "High") return "high";
  if (priority === "Low") return "low";
  return "medium";
}

function toFrontendPriority(priority: BackendTaskPriority): TaskPriority {
  if (priority === "urgent") return "Critical";
  if (priority === "high") return "High";
  if (priority === "low") return "Low";
  return "Medium";
}

function formatDueDate(value: string | null) {
  if (!value) return "";
  return value.slice(0, 16);
}

function parseSourceFormTemplateId(task: BackendTask) {
  if (task.source_type?.startsWith(LOCAL_FORM_TEMPLATE_PREFIX)) {
    return task.source_type.slice(LOCAL_FORM_TEMPLATE_PREFIX.length);
  }

  if (task.source_type === "form_template" && task.source_id) {
    return String(task.source_id);
  }

  return "";
}

function resolveTaskOutletHeader(form: TaskFormState) {
  if (form.recurrence === "once") {
    return form.outletId ?? form.targetOutletIds?.[0] ?? undefined;
  }

  return form.targetOutletIds?.[0] ?? form.outletId ?? undefined;
}

export function mapBackendTask(task: BackendTask): Task {
  const outletName = task.outlet_name ?? `Outlet ${task.outlet_id}`;
  const recurrence = task.recurrence ?? "once";
  const shifts: TaskShift[] =
    recurrence === "weekly" ? [] : task.shift ? [task.shift as TaskShift] : ["morning"];

  return {
    id: String(task.id),
    title: task.title,
    outlet: outletName,
    outletId: String(task.outlet_id),
    status: toFrontendStatus(task.status),
    priority: toFrontendPriority(task.priority),
    assignee: task.assigned_to ? `User ${task.assigned_to}` : "Outlet Team",
    due: formatDueDate(task.due_date),
    description: task.description ?? "",
    formTemplateId: parseSourceFormTemplateId(task),
    sourceType: task.source_type ?? undefined,
    sourceId: task.source_id != null ? String(task.source_id) : undefined,
    recurrence,
    shifts,
    targetOutlets: [outletName],
    autoPublish: task.auto_publish ?? false,
    dueTime: task.due_time ?? (formatDueDate(task.due_date).slice(11, 16) || "09:00"),
    weeklyPublishDay: (task.weekly_publish_day as Task["weeklyPublishDay"]) ?? "sunday",
    activity: [
      {
        id: `ACT-${task.id}-backend`,
        type: "created",
        title: task.schedule_id ? "Auto-published from schedule" : "Loaded from backend",
        description: task.schedule_id
          ? "This task was generated by a recurring schedule."
          : "This task is synced from NovaOps API.",
        actor: "NovaOps API",
        timestamp: task.updated_at,
      },
    ],
  };
}

function toBackendPayload(form: TaskFormState): BackendTaskCreate {
  const numericTemplateId = Number(form.formTemplateId);
  const isBackendTemplate = Number.isFinite(numericTemplateId);

  return {
    title: form.title.trim(),
    description: form.description.trim() || null,
    assigned_to: null,
    priority: toBackendPriority(form.priority),
    due_date: form.recurrence === "once" && form.due ? new Date(form.due).toISOString() : null,
    source_type: isBackendTemplate
      ? "form_template"
      : `${LOCAL_FORM_TEMPLATE_PREFIX}${form.formTemplateId}`,
    source_id: isBackendTemplate ? numericTemplateId : null,
  };
}

export const taskService = {
  async list(sourceType?: string) {
    try {
      const query = sourceType ? `?source_type=${encodeURIComponent(sourceType)}` : "";
      const tasks = await api<BackendTask[]>(`/api/v1/tasks${query}`);
      const mapped = tasks.map(mapBackendTask);
      if (!sourceType) {
        await cacheTasks(mapped);
      }
      return mapped;
    } catch (error) {
      if (!sourceType) {
        const cached = await getCachedTasks();

        if (cached.length > 0) {
          return cached;
        }
      }

      throw error;
    }
  },

  listAll() {
    return this.list();
  },

  async listCorrectiveActions() {
    return this.list("corrective_action");
  },

  async create(form: TaskFormState) {
    if (form.recurrence !== "once") {
      const schedule = await taskScheduleService.create(form);

      return {
        id: `SCHEDULE-${schedule.id}`,
        title: schedule.title,
        outlet: form.targetOutlets[0] ?? form.outlet,
        outletId: form.targetOutletIds?.[0] ?? form.outletId,
        status: "Pending",
        priority: form.priority,
        assignee: form.assignee,
        due: form.dueTime,
        description: form.description,
        formTemplateId: form.formTemplateId,
        recurrence: schedule.recurrence,
        shifts: form.shifts,
        targetOutlets: form.targetOutlets,
        autoPublish: schedule.auto_publish,
        dueTime: schedule.due_time,
        weeklyPublishDay: form.weeklyPublishDay,
      };
    }

    const task = await api<BackendTask>("/api/v1/tasks", {
      method: "POST",
      headers: resolveTaskOutletHeader(form)
        ? { "X-Outlet-Id": resolveTaskOutletHeader(form) as string }
        : undefined,
      body: JSON.stringify(toBackendPayload(form)),
    });
    return mapBackendTask(task);
  },

  async update(taskId: string, form: TaskFormState) {
    const payload: BackendTaskUpdate = toBackendPayload(form);
    const task = await api<BackendTask>(`/api/v1/tasks/${taskId}`, {
      method: "PATCH",
      body: JSON.stringify(payload),
    });
    return mapBackendTask(task);
  },

  async updateStatus(taskId: string, status: BackendTaskStatus) {
    const task = await api<BackendTask>(`/api/v1/tasks/${taskId}/status`, {
      method: "PATCH",
      body: JSON.stringify({ status }),
    });
    return mapBackendTask(task);
  },

  async remove(taskId: string, options?: { resolveOutletFromTask?: boolean }) {
    const headers: Record<string, string> = {};

    if (options?.resolveOutletFromTask) {
      headers["X-Outlet-Id"] = "";
    }

    return api<void>(`/api/v1/tasks/${taskId}`, {
      method: "DELETE",
      headers: Object.keys(headers).length > 0 ? headers : undefined,
    });
  },

  async review(taskId: string, review: "approved" | "rejected", note?: string) {
    const task = await api<BackendTask>(`/api/v1/tasks/${taskId}/review`, {
      method: "PATCH",
      body: JSON.stringify({ review, note: note ?? null }),
    });
    return mapBackendTask(task);
  },

  async submitExecution(
    taskId: string,
    payload: {
      form_template_id?: number | null;
      answers_json: Record<string, unknown>;
    }
  ) {
    const task = await api<BackendTask>(`/api/v1/tasks/${taskId}/submit-execution`, {
      method: "POST",
      body: JSON.stringify(payload),
    });
    return mapBackendTask(task);
  },
};
