"use client";

import { Bell, RefreshCw, Send } from "lucide-react";

import { useNotificationsWorkspace } from "@/features/notifications/hooks/use-notifications-workspace";
import type { NotificationDelivery } from "@/features/workflows/types";

function formatDate(value?: string | null) {
  if (!value) return "-";

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function getStatusTone(status: string) {
  switch (status) {
    case "sent":
      return "bg-emerald-50 text-emerald-700";
    case "failed":
      return "bg-rose-50 text-rose-700";
    case "processing":
      return "bg-blue-50 text-blue-700";
    case "cancelled":
      return "bg-slate-100 text-slate-500";
    default:
      return "bg-amber-50 text-amber-700";
  }
}

function NotificationCard({
  notification,
}: {
  notification: NotificationDelivery;
}) {
  return (
    <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Bell className="h-4 w-4 text-emerald-700" />
            <p className="truncate font-bold text-slate-950">
              {notification.subject ?? "NovaOps Notification"}
            </p>
          </div>

          <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">
            {notification.body}
          </p>
        </div>

        <span
          className={`inline-flex w-fit rounded-full px-3 py-1 text-xs font-bold ${getStatusTone(
            notification.status,
          )}`}
        >
          {notification.status}
        </span>
      </div>

      <div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 text-xs text-slate-500 sm:grid-cols-4">
        <div>
          <p className="font-bold uppercase tracking-wide text-slate-400">Channel</p>
          <p className="mt-1">{notification.channel}</p>
        </div>

        <div>
          <p className="font-bold uppercase tracking-wide text-slate-400">Attempts</p>
          <p className="mt-1">{notification.attempt_count}</p>
        </div>

        <div>
          <p className="font-bold uppercase tracking-wide text-slate-400">Created</p>
          <p className="mt-1">{formatDate(notification.created_at)}</p>
        </div>

        <div>
          <p className="font-bold uppercase tracking-wide text-slate-400">Sent</p>
          <p className="mt-1">{formatDate(notification.sent_at)}</p>
        </div>
      </div>

      {notification.last_error ? (
        <div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">
          {notification.last_error}
        </div>
      ) : null}
    </article>
  );
}

export function NotificationsWorkspace() {
  const workspace = useNotificationsWorkspace();

  async function processPending() {
    try {
      const result = await workspace.processPending();
      window.alert(JSON.stringify(result, null, 2));
    } catch (error) {
      window.alert(
        error instanceof Error ? error.message : "Failed to process notifications.",
      );
    }
  }

  return (
    <main className="space-y-6">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
        <div>
          <p className="text-sm font-medium text-emerald-700">Notification Engine</p>
          <h1 className="text-2xl font-semibold text-slate-950">Notification Inbox</h1>
          <p className="mt-1 max-w-2xl text-sm text-slate-500">
            Review notification deliveries generated by workflow and operational events.
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => void workspace.refetch()}
            className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700 shadow-sm hover:bg-slate-50"
          >
            <RefreshCw className="h-4 w-4" />
            Refresh
          </button>

          <button
            type="button"
            onClick={() => void processPending()}
            disabled={workspace.isProcessing}
            className="inline-flex items-center gap-2 rounded-2xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-emerald-800 disabled:opacity-50"
          >
            <Send className="h-4 w-4" />
            {workspace.isProcessing ? "Processing..." : "Process Pending"}
          </button>
        </div>
      </div>

      {workspace.isError ? (
        <div className="rounded-3xl border border-red-200 bg-red-50 p-5">
          <p className="font-bold text-red-700">Notification API error</p>
          <p className="mt-1 text-sm text-red-600">
            {workspace.error instanceof Error
              ? workspace.error.message
              : "Unable to load notifications."}
          </p>
        </div>
      ) : null}

      <section className="rounded-3xl border border-slate-200 bg-white p-5">
        <p className="text-sm font-bold text-slate-950">
          Total deliveries: {workspace.notifications.length}
        </p>
      </section>

      {workspace.isLoading ? (
        <div className="rounded-3xl border border-slate-200 bg-white p-8 text-sm text-slate-500">
          Loading notifications...
        </div>
      ) : workspace.notifications.length === 0 ? (
        <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center">
          <Bell className="mx-auto h-8 w-8 text-slate-300" />
          <p className="mt-3 font-bold text-slate-800">No notifications found</p>
          <p className="mt-1 text-sm text-slate-500">
            Process pending notification events or execute another workflow.
          </p>
        </div>
      ) : (
        <div className="grid gap-4">
          {workspace.notifications.map((notification) => (
            <NotificationCard key={notification.id} notification={notification} />
          ))}
        </div>
      )}
    </main>
  );
}
