import {
  WorkflowModule,
  WorkflowStatus,
  WorkflowStatusMeta,
  WorkflowTransition,
} from "../types/workflow";

export const WORKFLOW_MODULE_LABEL: Record<WorkflowModule, string> = {
  task: "Task",
  audit: "Audit",
  qa: "QA",
  foodsafety: "Food Safety",
  maintenance: "Maintenance",
  inventory: "Inventory",
  equipment: "Equipment",
  incident: "Incident",
  hr: "HR",
  document: "Document",
};

export const WORKFLOW_STATUS_META: Record<WorkflowStatus, WorkflowStatusMeta> = {
  draft: {
    status: "draft",
    label: "Draft",
    description: "Saved but not yet submitted or assigned.",
    tone: "neutral",
    isActionable: true,
  },
  assigned: {
    status: "assigned",
    label: "Assigned",
    description: "Assigned to an owner or outlet.",
    tone: "info",
    isActionable: true,
  },
  in_progress: {
    status: "in_progress",
    label: "In Progress",
    description: "Work has started and is currently active.",
    tone: "warning",
    isActionable: true,
  },
  submitted: {
    status: "submitted",
    label: "Submitted",
    description: "Submitted for review or approval.",
    tone: "purple",
    isActionable: true,
  },
  reviewed: {
    status: "reviewed",
    label: "Reviewed",
    description: "Reviewed by a supervisor or reviewer.",
    tone: "info",
  },
  approved: {
    status: "approved",
    label: "Approved",
    description: "Approved by the required approver.",
    tone: "success",
  },
  rejected: {
    status: "rejected",
    label: "Rejected",
    description: "Rejected by reviewer or approver.",
    tone: "danger",
    isTerminal: true,
  },
  revision_required: {
    status: "revision_required",
    label: "Revision Required",
    description: "Needs correction before it can proceed.",
    tone: "warning",
    isActionable: true,
  },
  completed: {
    status: "completed",
    label: "Completed",
    description: "Workflow has been fully completed.",
    tone: "success",
    isTerminal: true,
  },
  cancelled: {
    status: "cancelled",
    label: "Cancelled",
    description: "Workflow has been cancelled.",
    tone: "neutral",
    isTerminal: true,
  },
  overdue: {
    status: "overdue",
    label: "Overdue",
    description: "Workflow has passed its SLA or due date.",
    tone: "danger",
    isActionable: true,
  },
  blocked: {
    status: "blocked",
    label: "Blocked",
    description: "Workflow cannot continue due to a blocker.",
    tone: "danger",
    isActionable: true,
  },
};

export const WORKFLOW_TRANSITIONS: WorkflowTransition[] = [
  {
    from: "draft",
    to: "assigned",
    action: "assign",
    label: "Assign",
    requiresAssignee: true,
  },
  {
    from: "draft",
    to: "in_progress",
    action: "start",
    label: "Start",
  },
  {
    from: "assigned",
    to: "in_progress",
    action: "start",
    label: "Start Work",
  },
  {
    from: "in_progress",
    to: "submitted",
    action: "submit",
    label: "Submit",
  },
  {
    from: "submitted",
    to: "reviewed",
    action: "review",
    label: "Mark Reviewed",
  },
  {
    from: "submitted",
    to: "approved",
    action: "approve",
    label: "Approve",
  },
  {
    from: "reviewed",
    to: "approved",
    action: "approve",
    label: "Approve",
  },
  {
    from: "submitted",
    to: "revision_required",
    action: "request_revision",
    label: "Request Revision",
    requiresReason: true,
  },
  {
    from: "reviewed",
    to: "revision_required",
    action: "request_revision",
    label: "Request Revision",
    requiresReason: true,
  },
  {
    from: "revision_required",
    to: "in_progress",
    action: "reopen",
    label: "Reopen",
  },
  {
    from: "approved",
    to: "completed",
    action: "complete",
    label: "Complete",
  },
  {
    from: "draft",
    to: "cancelled",
    action: "cancel",
    label: "Cancel",
    requiresReason: true,
  },
  {
    from: "assigned",
    to: "cancelled",
    action: "cancel",
    label: "Cancel",
    requiresReason: true,
  },
  {
    from: "in_progress",
    to: "cancelled",
    action: "cancel",
    label: "Cancel",
    requiresReason: true,
  },
  {
    from: "assigned",
    to: "overdue",
    action: "mark_overdue",
    label: "Mark Overdue",
  },
  {
    from: "in_progress",
    to: "overdue",
    action: "mark_overdue",
    label: "Mark Overdue",
  },
  {
    from: "overdue",
    to: "in_progress",
    action: "reopen",
    label: "Reopen",
  },
  {
    from: "assigned",
    to: "blocked",
    action: "block",
    label: "Block",
    requiresReason: true,
  },
  {
    from: "in_progress",
    to: "blocked",
    action: "block",
    label: "Block",
    requiresReason: true,
  },
  {
    from: "blocked",
    to: "in_progress",
    action: "unblock",
    label: "Unblock",
  },
];
