"""sync task management models

Revision ID: 2f6520082e9b
Revises: 8334cd3ee383
Create Date: 2026-07-03 00:13:13.616796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6520082e9b'
down_revision: Union[str, Sequence[str], None] = '8334cd3ee383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.alter_column('outlets', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_constraint(op.f('outlets_code_key'), 'outlets', type_='unique')
    op.create_index(op.f('ix_outlets_code'), 'outlets', ['code'], unique=True)
    op.create_index(op.f('ix_outlets_organization_id'), 'outlets', ['organization_id'], unique=False)
    op.drop_column('outlets', 'city')
    op.create_index(op.f('ix_user_outlet_roles_id'), 'user_outlet_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_outlet_roles_organization_id'), 'user_outlet_roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_outlet_roles_outlet_id'), 'user_outlet_roles', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_user_outlet_roles_user_id'), 'user_outlet_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_outlet_roles_user_id'), table_name='user_outlet_roles')
    op.drop_index(op.f('ix_user_outlet_roles_outlet_id'), table_name='user_outlet_roles')
    op.drop_index(op.f('ix_user_outlet_roles_organization_id'), table_name='user_outlet_roles')
    op.drop_index(op.f('ix_user_outlet_roles_id'), table_name='user_outlet_roles')
    op.add_column('outlets', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_outlets_organization_id'), table_name='outlets')
    op.drop_index(op.f('ix_outlets_code'), table_name='outlets')
    op.create_unique_constraint(op.f('outlets_code_key'), 'outlets', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('outlets', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
