"""add workflow approval matrix

Revision ID: 3e494578a675
Revises: e85ea046ecd5
Create Date: 2026-07-07 16:10:47.756234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e494578a675'
down_revision: Union[str, Sequence[str], None] = 'e85ea046ecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_approval_matrices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('approver_type', sa.Enum('role', 'user', 'outlet', 'area_manager', name='workflowapprovertype'), nullable=False),
    sa.Column('approver_role_id', sa.UUID(), nullable=True),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_role_id'], ['identity_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['identity_outlets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approval_matrices_step_id'), 'workflow_approval_matrices', ['step_id'], unique=False)
    op.create_index(op.f('ix_workflow_approval_matrices_workflow_id'), 'workflow_approval_matrices', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_approval_matrices_workflow_id'), table_name='workflow_approval_matrices')
    op.drop_index(op.f('ix_workflow_approval_matrices_step_id'), table_name='workflow_approval_matrices')
    op.drop_table('workflow_approval_matrices')
    # ### end Alembic commands ###
