"""add workflow approval history

Revision ID: 594a5f97279f
Revises: b46bba7b47cb
Create Date: 2026-07-07 16:36:47.410016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '594a5f97279f'
down_revision: Union[str, Sequence[str], None] = 'b46bba7b47cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_approval_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('instance_step_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('submitted', 'approved', 'rejected', 'returned', 'cancelled', 'completed', 'escalated', 'skipped', name='workflowactiontype'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_step_id'], ['workflow_instance_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approval_history_action_type'), 'workflow_approval_history', ['action_type'], unique=False)
    op.create_index(op.f('ix_workflow_approval_history_actor_user_id'), 'workflow_approval_history', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_approval_history_instance_id'), 'workflow_approval_history', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_approval_history_instance_step_id'), 'workflow_approval_history', ['instance_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_approval_history_instance_step_id'), table_name='workflow_approval_history')
    op.drop_index(op.f('ix_workflow_approval_history_instance_id'), table_name='workflow_approval_history')
    op.drop_index(op.f('ix_workflow_approval_history_actor_user_id'), table_name='workflow_approval_history')
    op.drop_index(op.f('ix_workflow_approval_history_action_type'), table_name='workflow_approval_history')
    op.drop_table('workflow_approval_history')
    # ### end Alembic commands ###
