"""create enterprise identity tables

Revision ID: 6f6f39c705e4
Revises: 260705_uor_audit_cols
Create Date: 2026-07-06 01:43:52.117223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6f39c705e4'
down_revision: Union[str, Sequence[str], None] = '260705_uor_audit_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_organizations_code'), 'identity_organizations', ['code'], unique=True)
    op.create_index(op.f('ix_identity_organizations_id'), 'identity_organizations', ['id'], unique=False)
    op.create_table('identity_permissions',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_permissions_code'), 'identity_permissions', ['code'], unique=True)
    op.create_index(op.f('ix_identity_permissions_id'), 'identity_permissions', ['id'], unique=False)
    op.create_table('identity_roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_roles_id'), 'identity_roles', ['id'], unique=False)
    op.create_index(op.f('ix_identity_roles_slug'), 'identity_roles', ['slug'], unique=True)
    op.create_table('identity_outlets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['identity_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_outlets_code'), 'identity_outlets', ['code'], unique=True)
    op.create_index(op.f('ix_identity_outlets_id'), 'identity_outlets', ['id'], unique=False)
    op.create_index(op.f('ix_identity_outlets_organization_id'), 'identity_outlets', ['organization_id'], unique=False)
    op.create_table('identity_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['identity_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['identity_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('identity_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['identity_outlets.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['identity_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_users_email'), 'identity_users', ['email'], unique=True)
    op.create_index(op.f('ix_identity_users_id'), 'identity_users', ['id'], unique=False)
    op.create_index(op.f('ix_identity_users_outlet_id'), 'identity_users', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_identity_users_role_id'), 'identity_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_identity_users_username'), 'identity_users', ['username'], unique=True)
    op.create_table('identity_audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['identity_organizations.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['identity_outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_audit_logs_actor_user_id'), 'identity_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_identity_audit_logs_id'), 'identity_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_identity_audit_logs_organization_id'), 'identity_audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_identity_audit_logs_outlet_id'), 'identity_audit_logs', ['outlet_id'], unique=False)
    op.create_table('identity_refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_refresh_tokens_id'), 'identity_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_identity_refresh_tokens_token_hash'), 'identity_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_identity_refresh_tokens_user_id'), 'identity_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_refresh_tokens_user_id'), table_name='identity_refresh_tokens')
    op.drop_index(op.f('ix_identity_refresh_tokens_token_hash'), table_name='identity_refresh_tokens')
    op.drop_index(op.f('ix_identity_refresh_tokens_id'), table_name='identity_refresh_tokens')
    op.drop_table('identity_refresh_tokens')
    op.drop_index(op.f('ix_identity_audit_logs_outlet_id'), table_name='identity_audit_logs')
    op.drop_index(op.f('ix_identity_audit_logs_organization_id'), table_name='identity_audit_logs')
    op.drop_index(op.f('ix_identity_audit_logs_id'), table_name='identity_audit_logs')
    op.drop_index(op.f('ix_identity_audit_logs_actor_user_id'), table_name='identity_audit_logs')
    op.drop_table('identity_audit_logs')
    op.drop_index(op.f('ix_identity_users_username'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_role_id'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_outlet_id'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_id'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_email'), table_name='identity_users')
    op.drop_table('identity_users')
    op.drop_table('identity_role_permissions')
    op.drop_index(op.f('ix_identity_outlets_organization_id'), table_name='identity_outlets')
    op.drop_index(op.f('ix_identity_outlets_id'), table_name='identity_outlets')
    op.drop_index(op.f('ix_identity_outlets_code'), table_name='identity_outlets')
    op.drop_table('identity_outlets')
    op.drop_index(op.f('ix_identity_roles_slug'), table_name='identity_roles')
    op.drop_index(op.f('ix_identity_roles_id'), table_name='identity_roles')
    op.drop_table('identity_roles')
    op.drop_index(op.f('ix_identity_permissions_id'), table_name='identity_permissions')
    op.drop_index(op.f('ix_identity_permissions_code'), table_name='identity_permissions')
    op.drop_table('identity_permissions')
    op.drop_index(op.f('ix_identity_organizations_id'), table_name='identity_organizations')
    op.drop_index(op.f('ix_identity_organizations_code'), table_name='identity_organizations')
    op.drop_table('identity_organizations')
    # ### end Alembic commands ###
