"""add workflow instance engine

Revision ID: b46bba7b47cb
Revises: 3e494578a675
Create Date: 2026-07-07 16:25:54.608803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b46bba7b47cb'
down_revision: Union[str, Sequence[str], None] = '3e494578a675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'pending_approval', 'approved', 'rejected', 'returned', 'cancelled', 'completed', name='workflowinstancestatus'), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_entity_id'), 'workflow_instances', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_type'), 'workflow_instances', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_instances_module'), 'workflow_instances', ['module'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_id'), 'workflow_instances', ['workflow_id'], unique=False)
    op.create_table('workflow_instance_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('workflow_step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'approved', 'rejected', 'returned', 'skipped', name='workflowinstancestepstatus'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_role_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['identity_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instance_steps_instance_id'), 'workflow_instance_steps', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_instance_steps_workflow_step_id'), 'workflow_instance_steps', ['workflow_step_id'], unique=False)
    op.create_table('workflow_variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_variables_instance_id'), 'workflow_variables', ['instance_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('instance_step_id', sa.UUID(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('assignee_role_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_role_id'], ['identity_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_step_id'], ['workflow_instance_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_instance_id'), 'workflow_tasks', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_instance_step_id'), 'workflow_tasks', ['instance_step_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_instance_step_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_instance_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_workflow_variables_instance_id'), table_name='workflow_variables')
    op.drop_table('workflow_variables')
    op.drop_index(op.f('ix_workflow_instance_steps_workflow_step_id'), table_name='workflow_instance_steps')
    op.drop_index(op.f('ix_workflow_instance_steps_instance_id'), table_name='workflow_instance_steps')
    op.drop_table('workflow_instance_steps')
    op.drop_index(op.f('ix_workflow_instances_workflow_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_module'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    # ### end Alembic commands ###
