"""add workflow definition engine

Revision ID: e85ea046ecd5
Revises: 20260707_0010
Create Date: 2026-07-07 15:54:23.963356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e85ea046ecd5'
down_revision: Union[str, Sequence[str], None] = '20260707_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='workflowdefinitionstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_code'), 'workflow_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_workflow_definitions_module'), 'workflow_definitions', ['module'], unique=False)
    op.create_table('workflow_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expression_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_conditions_workflow_id'), 'workflow_conditions', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.Enum('start', 'approval', 'task', 'condition', 'end', name='workflowsteptype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('from_step_id', sa.UUID(), nullable=False),
    sa.Column('to_step_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['workflow_conditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_transitions_workflow_id'), 'workflow_transitions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_identity_outlet_operators_id'), 'identity_outlet_operators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_outlet_operators_id'), table_name='identity_outlet_operators')
    op.drop_index(op.f('ix_workflow_transitions_workflow_id'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_conditions_workflow_id'), table_name='workflow_conditions')
    op.drop_table('workflow_conditions')
    op.drop_index(op.f('ix_workflow_definitions_module'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_code'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
