"""add workflow escalation rules

Revision ID: efdfce4fb16a
Revises: 594a5f97279f
Create Date: 2026-07-07 16:51:32.784591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efdfce4fb16a'
down_revision: Union[str, Sequence[str], None] = '594a5f97279f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_escalation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_after_hours', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('notify', 'escalate', 'auto_approve', 'auto_reject', name='workflowescalationaction'), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['identity_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['identity_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_escalation_rules_step_id'), 'workflow_escalation_rules', ['step_id'], unique=False)
    op.create_index(op.f('ix_workflow_escalation_rules_workflow_id'), 'workflow_escalation_rules', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_escalation_rules_workflow_id'), table_name='workflow_escalation_rules')
    op.drop_index(op.f('ix_workflow_escalation_rules_step_id'), table_name='workflow_escalation_rules')
    op.drop_table('workflow_escalation_rules')
    # ### end Alembic commands ###
